name: Build image and apply Terraform

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build-and-apply:
    runs-on: ubuntu-latest
    env:
      GCP_PROJECT: gcp-terraform-demo-474514
      GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure credentials file for tools
        run: |
          echo "${{ secrets.GCP_SA_KEY }}" > /tmp/gcp-key.json
          echo "GOOGLE_APPLICATION_CREDENTIALS=/tmp/gcp-key.json" >> $GITHUB_ENV

      - name: Setup Packer
        uses: hashicorp/setup-packer@v1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      - name: Packer init and build image
        working-directory: packer
        run: |
          packer init .
          packer build -var "project=${{ env.GCP_PROJECT }}" -var "image_name=custom-apache-image-${{ github.run_id }}" template.pkr.hcl

      - name: Terraform fmt
        run: terraform fmt -check=false

      - name: Terraform init
        run: terraform init

      - name: Terraform apply
        run: terraform apply -auto-approve -var "image_name=custom-apache-image-${{ github.run_id }}" -var-file="dev.tfvars"
