name: Build image and apply Terraform

on:
  workflow_dispatch:

jobs:
  build-and-apply:
    runs-on: ubuntu-latest
    env:
      GCP_PROJECT: gcp-terraform-demo-474514
      GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure credentials file for tools
        run: |
          echo "${{ secrets.GCP_SA_KEY }}" | base64 -d > /tmp/gcp-key.json
          echo "GOOGLE_APPLICATION_CREDENTIALS=/tmp/gcp-key.json" >> $GITHUB_ENV

      - name: Install Packer
        run: |
          set -eux
          sudo apt-get update
          sudo apt-get install -y gnupg software-properties-common curl unzip
          curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
          sudo apt-get update
          sudo apt-get install -y packer

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      - name: Packer init and build image
        working-directory: packer
        run: |
          packer init .
          packer build -var "project_id=${{ env.GCP_PROJECT }}" -var "image_name=custom-apache-image-${{ github.run_id }}" template.pkr.hcl

      - name: Terraform fmt
        run: terraform fmt -check=false

      - name: Terraform init
        run: terraform init

      - name: Terraform apply
        run: terraform apply -auto-approve -var "image_name=custom-apache-image-${{ github.run_id }}" -var-file="dev.tfvars"
